### ISSUE TITLE
allow bulk assignment of paper administrator

### ISSUE THREAD

**Issue by JuliaLawall** [kohler/hotcrp#178]
When there are a large number of submissions and multiple PC chairs, each PC member may want to receive email about only the papers they are responsible for.  Currently it seems that the only way to do this is to go to every paper, and then select the relevant PC member in a pull down menu that contains the entire PC, which is highly error prone.  The other option is to extract the command sent by the browser when such a selection is made, and then write a shell script that runs that command for each PC member and their associated papers, but this is obviously not ideal.

**Comment by JuliaLawall** [comment]
It seems that the administrator functionality does not give the chair everything we hoped for, because we are still both getting all reviews by email.  So perhaps what we want is to be able to script the unchecking of the Email notification box.

**Comment by kohler** [comment]
Hi Julia,

First of all, bulk assignment *did* support setting administrators, with an “administrator” action. But this wasn't obvious to you because it wasn't mentioned in the UI. It is now.

Furthermore, I debugged why the administrator functionality was not giving you everything you hoped for. You must have selected “notify me about updates for…papers I administer”. This formerly included all papers you *COULD* administer, including papers that had a different, explicitly-assigned administrator. But this was confusing and what you expected was better. Now you should be only getting notifications about papers for which you are the primary administrator.

Further furthermore, I added a “follow” bulk assignment type so that you can script the email notification box using bulk assignment.

Thanks for this report.

**Comment by JuliaLawall** [comment]
On Mon, 10 Jun 2019, Eddie Kohler wrote:

>
> Hi Julia,
>
> First of all, bulk assignment did support setting administrators, with an
> “administrator” action. But this wasn't obvious to you because it wasn't
> mentioned in the UI. It is now.
>
> Furthermore, I debugged why the administrator functionality was not giving
> you everything you hoped for. You must have selected “notify me about
> updates for…papers I administer”. This formerly included all papers you
> COULD administer, including papers that had a different, explicitly-assigned
> administrator. But this was confusing and what you expected was better. Now
> you should be only getting notifications about papers for which you are the
> primary administrator.
>
> Further furthermore, I added a “follow” bulk assignment type so that you can
> script the email notification box using bulk assignment.
>
> Thanks for this report.

Thanks for all of this!

julia
