### ISSUE TITLE
Support hard limit on author rebuttal

### ISSUE THREAD

**Issue by seattleplus** [kohler/hotcrp#230]
As far as I can tell, the limit on author rebuttals is only a soft limit and it is not possible to implement a hard limit. 

For authors, some stick to the limit and may have felt they could have added more information if the limit was higher, and for other authors they completely ignore the limit and add way to much information.  This creates an unfair playing field for authors.

For reviewers, confusion is created when authors go beyond the soft limit as to whether they need to read the entire rebuttal or only the text below the soft limit.

A hard limit would be one good way to level the playing field and avoid confusion.  This gives control to chairs on how they would like to manage fairness among authors and load for the reviewers.
Thanks!

**Comment by emeryberger** [comment]
Not that I oppose the addition of this feature, but I am posting this because it might be useful to you (and others) in the likely event that this feature is not added soon.

For ASPLOS'21, we specifically sought to place authors on a level playing field. We sent them this document, which provides detailed guidance on how authors should write their responses and what the guidance was for reviewers: [ASPLOS'21 Instructions for Author Response](https://docs.google.com/document/d/1qbcHnL6OGm8seJNlWMRwKEC519j9kzIcVdqTBRa0XIw/edit?usp=sharing
).

I'll just quote the first paragraph here. Feel free to use or adapt this text freely.

> For ASPLOS'21, the author response will not be limited in length. However, there will be a soft limit of 500 words. Reviewers will not be required to read more than this number of words. However, they will be interested in reading your responses to their specific questions.

**Comment by seattleplus** [comment]
Thanks Emery, this is basically what I'm seeing most conferences do at this point...not sure if it is because it is the desired method or because this is what hotcrp allows.  The guidance though is great, and I'm sure it helped a lot. (and thanks for the willingness to share)

My recent experience though is that many reviewers won't in good conscience not read past the 500 word mark if it helps them better evaluate the paper...as their goal is to accept the best papers and use all information at their disposal to do so.  So I still believe that a hard limit to reign in the worst tendencies (probably in addition to a soft limit) and help reduce reviewer burden would be of great value.

I'll add that at a recent conference, the chairs had the lead reviewer summarize the key items to which the author should respond and write it up as a author-visible comment.  This was very helpful to keep the authors on track for the first 500 words.  I could imagine this 'key items to respond to' being an entire field unto itself (instead of being only in each review).

**Comment by kohler** [comment]
I think HotCRP's existing soft limit is better than hard limits. A fair amount of work went into displaying the soft limit so people can stop reading. (Text beyond the soft limit is shaded.) And I know many conferences prefer soft limits, or advise that authors use the soft limit for responses to general themes and use space beyond the soft limit for responses to specific reviewers.

Would you prefer or like to work on one of the following? It's open source.

* A hard limit in addition to the soft limit (i.e. response display is cut off after N words)
* A different presentation of the soft limit (e.g. an expander button, so that stuff beyond the soft limit is not displayed by default)

**Comment by seattleplus** [comment]
Thanks for the reply! 

Right, I wouldn't eliminate the soft limit if others find value in it...so I like the notion of adding a hard limit (your first suggestion).  Since I'm in storage we could compare to how storage systems typically implement capacity quotas...there is a warning and then there is E_NOSPC 👍 

I like the current rebuttal presentation, but if anything I'd make the entire rebuttal easier to view (not harder to view). An expander button, etc would in my opinion cause even more confusion, with PC members possibly missing out on information they would have liked to have read.  Similar to how we control paper limits, I'd probably set the soft and hard quotas to the same value and eliminate any confusion for authors or PC members.

**Comment by kohler** [comment]
I understand that you like the notion of adding a hard limit, and that you have analogies, but will you work on a hard limit patch?

For myself, I got interested in changing the presentation of the soft limit, and have done so. I am curious on your feedback. It is deployed on test.hotcrp.com, visible on paper 1, and on hotcrp.com more broadly.

**Comment by dants** [comment]
I'd like to comment that I personally know many who regularly serve as both authors and reviewers, and who are thankful for and greatly appreciate the fact that hotcrp does NOT support a hard limit on rebuttals, which they feel would undoubtedly cause more harm than good. 

Because (**1**) program chairs instruct reviewers to ignore text that exceed the limit if they so choose, and because (**2**) it's arguably preferable to let them choose (I know I want to have this option rather than have somebody decide for me), and because (**3**) they seldom (if at all) constrain or coordinate their questions so as to allow responses to meet some arbitrary limit, and because (**4**) they actually sometimes want answers to their questions, and the answers might need more space than some arbitrary limit, and because (**5**) reading rebuttal that exceed the soft limit is still orders of magnitude less time-consuming than reviewing the corresponding submissions, and because (**6**) rebuttals often requires a lot of work from authors as it is, whereas their value is questioned by very many -- then further burdening authors with a hard rebuttal limit seems counterproductive.

Please, let the limit remain soft.

**Comment by kohler** [comment]
Gonna close this issue. If anyone strongly prefers the old presentation of soft limits to the new presentation, feel free to comment below.

New presentation, unexpanded:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/410647/115717792-86d4d500-a348-11eb-9496-388224c4bce0.png">

Expanded:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/410647/115717838-90f6d380-a348-11eb-87e7-d73755a1affc.png">

**Comment by fdouglis** [comment]
I was pointed at this when raising it via email.  I think the soft limit is a great idea, and I thank Eddie for the very nice implementation of it. 

That being said, I think there should also be a hard limit.  It could be disabled by default, or a reasonable multiplier of the soft limit, such as 750/500.  But I absolutely think there should be a hard limit option, because as a program chair, I just had someone submit 4600 words for a soft limit of 500, and that just pisses everyone off.  Sure, people can stop reading at 500, but you've gotta draw a line somewhere.   I'm inclined to delete it completely.  

The next question from Eddie is no doubt if I'd like to implement it.  Maybe ....  I have never looked at the HotCRP source, though now that I'm over here on github that's easy enough so I can at least see, for instance, what language it uses!

**Comment by kohler** [comment]
> (UPDATE: php? No, sorry, I will not be implementing.)

I hope you enjoyed writing that in that tone! I did not enjoy reading it.

**Comment by fdouglis** [comment]
Eddie, I did not mean to give offense!!! I just meant that I have no idea how to program in PHP, so I don't expect to try to pick it up just for this exercise.   PHP may be absolutely wonderful.  I toyed with it a great many years ago.  But I was hoping this was python or something I could simply pick up.

**Comment by JuliaLawall** [comment]
Thanks!  But at risk of asking for too many things, would it be possible to have both a soft and a hard limit?  The soft limit would be what reviewers naturally see and the hard limit would be the point at which responses are truncated.  For ATC this year we asked for 500 words and then said that responses over 1000 words might be rejected.  A lot of responses came in at or just under 500, some at or just under 1000, and maybe a third with various numbers between 500 and 1000.  There was only one major violation, but we spent a lot of time discussing what to do about it.

**Comment by kohler** [comment]
You could implement it as a pull request. Start from b782f9e11e2735baddee7fa578caf4d872afab46. However, I think it’s misguided to litigate or overspecify policies, or, especially, to disable useful functionality out of fear of an edge case (#304). PC chairs can delete any response, whether or not it fits a length limit (e.g. a response might be abusive in tone), and it is good for the community for PC chairs to use their human discretion.
