### ISSUE TITLE
Issue with hyperlinks to other pages missing .php

### ISSUE THREAD

**Issue by Nocturnal00p** [kohler/hotcrp#288]
Hello. 
So I noticed that the href attribute in links will point to "forgotpassword" but not "forgotpassword.php". 
When I click the links, it says page cannot be found as it tries to navigate to HotCRP/forgotpassword.
When I manually add .php to the href attribute (i.e. forgotpassword.php) the links work just fine.

I found a file `src/siteloader.php` that I believe is supposed to handle this by checking if the href is a specified shortcut and if not append .php to it. For some reason this mechanism isn't working.

I checked file permissions on my server....currently all the files are 775. So I don't think it is an issue with the script being blocked from execution.

Any advice on what is going on? Will I need to manually edit all the href attributes to get this working?

**Comment by kohler** [comment]
Hi, I assume you were using an Apache setup rather than nginx. Nginx is recommended and the README instructions for nginx didn't have this issue. However, the README was updated, since you reported this problem, with better instructions for Apache; please reopen if you still experience a problem with those instructions.
