### ISSUE TITLE
JSON download contains inconsistent field names

### ISSUE THREAD

**Issue by VictorLeP** [kohler/hotcrp#327]
Site: https://sec24summerae.usenix.hotcrp.com/

When I do a download of "Paper information" > "JSON", the resulting JSON has (a.o.) these three fields:
```
        "artifacts_available_badge": true,
        "artifacts_functional_badge": true,
        "opt5": true,
```

which correspond to these three entries on the submission form: 
![Schermafdruk van 2023-11-02 11-29-46](https://github.com/kohler/hotcrp/assets/6874341/d9fb05b3-53c2-4bed-9e94-ea4331a14a04)

I checked in the advanced settings that the `"Results Reproduced" badge` entry indeed has as its ID `5`, and the values correspond to what I see on the website.

The question is: why are the JSON field names for the first two entries "readable", i.e., based on their name on the submission form, while for the third entry it defaults to `opt{ID}`? I've looked through the (advanced) settings, but I do not see something that suggests I can configure these field names myself.

**Comment by kohler** [comment]
This is an ambiguity issue with your review form. You have:

* Submission field `"Artifacts Available" badge`
* Submission field `"Artifacts Functional" badge`
* Submission field `"Results Reproduced" badge`
* Review field `Artifact available badge` (note singular not plural)
* Review field `Artifact functional badge`
* Review field `Results reproduced badge`

Because the review field & the submission field for “results reproduced badge” have the same name (ignoring punctuation and case), HotCRP gives up abbreviating them and reverts to ID-based names. You lucked out with the artifact badges because of singular vs. plural. You're right that the supported keywords are not currently configurable.

**Comment by VictorLeP** [comment]
Ah, makes sense, thanks for the explanation!

Should I close the issue because my question is answered, or leave it open to track "supported keywords are not currently configurable"?
