### ISSUE TITLE
Remove withdraw button after rebuttal starts

### ISSUE THREAD

**Issue by ekinoguz** [kohler/hotcrp#59]
Some conferences ([example](http://www.ieee-security.org/TC/SP2015/cfpapers.html)) do not allow to withdraw the paper between the start of the author response period and acceptance notification. However, system still shows the Withdraw button, and even allow author to withdraw the paper.

This is definitely confusing since author is actually not allowed to withdraw.

@kohler thoughts?

**Comment by ericbodden** [comment]
@ekinoguz for ISSTA we do allow this, so it would be good to at least have this as an option.

**Comment by kohler** [comment]
In current HotCRP, withdrawal becomes impossible as soon as an author sees a review. @ericbodden if ISSTA really needs the withdrawal functionality maybe open another issue with that; I think it's generally good to prevent withdrawal in that case, since withdrawal-after-review should be rare. (It is the same as reject-after-review.)

**Comment by ericbodden** [comment]
@kohler ISSTA uses a two-phase review process. It's fairly common that authors wish to withdraw their papers after receiving negative reviews in phase 1. For the PC this is also desirable, as those papers then do not have to be considered any further.
